name: Chromium Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Install reporter
        run: dotnet tool update dotnet-reportgenerator-globaltool --tool-path ./reporter/ 
      - name: Run tests
        env:
          PRODUCT: CHROMIUM
        run: dotnet test ./src/PlaywrightSharp.Tests/PlaywrightSharp.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./artifacts
      - name: Run Coverage
        if: always()
        run: ./reporter/reportgenerator "-reports:../artifacts/coverage.cobertura.xml" "-targetdir:../artifacts/" -reportTypes:htmlInline 
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1.0.0
        if: always()
        with:
          name: artifacts
          path: artifacts

          dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools